# Generated by Django 5.0.6 on 2024-06-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
