# Generated by Django 5.0.6 on 2024-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_profile_bmi_alter_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(blank=True, choices=[('Cardio', 'Cardio'), ('Weight-Lifting', 'Weight-Lifting'), ('Calisthenics', 'Calisthenics'), ('HIIT', 'HIIT'), ('Crossfit', 'Crossfit')], max_length=20),
        ),
    ]
