# Generated by Django 5.0.6 on 2024-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_workoutsession_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Weight-Lifting', 'Weight-Lifting'), ('Calisthenics', 'Calisthenics'), ('HIIT', 'HIIT'), ('Crossfit', 'Crossfit')], default='Cardio', max_length=20),
        ),
    ]
