# Generated by Django 5.0.6 on 2024-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Goal_BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Goal_Weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.TimeField(blank=True),
        ),
    ]
