# Generated by Django 5.0.6 on 2024-06-27 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_profile_goal_bmi_profile_goal_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 6, 27, 12, 44, 15, 101644, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 6, 27, 12, 44, 30, 31973, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='duration',
            field=models.DurationField(),
        ),
    ]
