# Generated by Django 5.0.6 on 2024-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_workoutsession_end_time_workoutsession_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='curr_body_weight',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
