# Generated by Django 5.0.6 on 2024-07-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_weightheightentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BMI',
        ),
        migrations.AlterField(
            model_name='weightheightentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.profile'),
        ),
    ]
